apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: playbook-dispatcher-connect
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-pipeline-tenant/playbook-dispatcher/playbook-dispatcher-connect@sha256:552a3e866375988afa1d15a3c191a98e7cc01911e51f0f58c73f30e6b7832b4d
        name: container-image
        resources: {}
status: {}
