apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: playbook-dispatcher-connect
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-pipeline-tenant/playbook-dispatcher/playbook-dispatcher-connect@sha256:bf29453e71629e3b51c7e39f791493b3435577cca6a5a53c154788280e568909
        name: container-image
        resources: {}
status: {}
