apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: playbook-dispatcher-connect
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-pipeline-tenant/playbook-dispatcher/playbook-dispatcher-connect@sha256:10464cd1fe1587f83661831a0b9b4e997c7effc2eff619d6367421ebbd2526fe
        name: container-image
        resources: {}
status: {}
