apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: playbook-dispatcher
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: playbook-dispatcher
    app.kubernetes.io/part-of: playbook-dispatcher
  name: playbook-dispatcher
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: playbook-dispatcher
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: playbook-dispatcher
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-pipeline-tenant/playbook-dispatcher/playbook-dispatcher@sha256:cd6f581b88e1f95e715b9ed3805b88f892754896aba748d9d7d65b932c814cc0
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
status: {}
