apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: playbook-dispatcher-connect
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: playbook-dispatcher-connect
    app.kubernetes.io/part-of: playbook-dispatcher
  name: playbook-dispatcher-connect
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: playbook-dispatcher-connect
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: playbook-dispatcher-connect
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-pipeline-tenant/playbook-dispatcher/playbook-dispatcher-connect@sha256:79eaaf48947ef5514c75aa6e05971196cea12ee3c3c587a29c83e42dc25c4c60
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
status: {}
